name: Run Unit Tests

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]
    workflow_dispatch:

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/unit-tests.yml@master
